id: 1bc0d567-151e-4b69-8c01-fbffb3486890
version: 1
vcShouldKeepItemLegacyProdMachine: false
name: Cortex ASM - Initialize
description: This playbook takes care of initialization in case the playbook is re-run
  on the alert was created before the fields were installed through content pack.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0f976c7b-0dcb-4564-84a9-ddd933cc192e
    type: start
    task:
      id: 0f976c7b-0dcb-4564-84a9-ddd933cc192e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 40
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 13646489-97e2-4975-8115-eee9ad822f93
    type: title
    task:
      id: 13646489-97e2-4975-8115-eee9ad822f93
      version: -1
      name: Initialize Grid Fields
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
      - "4"
      - "7"
      - "6"
      - "11"
      - "10"
      - "13"
      - "16"
      - "12"
      - "17"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 490,
          "y": 300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 13b31f02-5986-4afa-8dbe-90b193cfc98c
    type: regular
    task:
      id: 13b31f02-5986-4afa-8dbe-90b193cfc98c
      version: -1
      name: Initialize `ASM - Private IP`
      description: Resets grid field to [] in the case that the playbook was run again
        or if the alert was created before the field was installed through content.
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      asmprivateip:
        simple: '[]'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -650,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 067b1d50-dfbb-4768-81ed-26d7c7a295cf
    type: regular
    task:
      id: 067b1d50-dfbb-4768-81ed-26d7c7a295cf
      version: -1
      name: Initialize `ASM - Service Owner`
      description: Resets grid field to [] in the case that the playbook was run again
        or if the alert was created before the field was installed through content.
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      asmserviceowner:
        simple: '[]'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -270,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 692c560a-36e0-4967-8613-89195041f2e9
    type: regular
    task:
      id: 692c560a-36e0-4967-8613-89195041f2e9
      version: -1
      name: Initialize `ASM - System IDs`
      description: Resets grid field to [] in the case that the playbook was run again
        or if the alert was created before the field was installed through content.
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      asmsystemids:
        simple: '[]'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 490,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: a178fb3f-67b4-4919-8948-025117585db0
    type: regular
    task:
      id: a178fb3f-67b4-4919-8948-025117585db0
      version: -1
      name: Initialize `ASM - Tags`
      description: Resets grid field to [] in the case that the playbook was run again
        or if the alert was created before the field was installed through content.
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      asmtags:
        simple: '[]'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 110,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: ec53220a-21e6-4538-8663-411b77ddc670
    type: title
    task:
      id: ec53220a-21e6-4538-8663-411b77ddc670
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 4f2512b8-f320-43ea-8647-787365c981fa
    type: regular
    task:
      id: 4f2512b8-f320-43ea-8647-787365c981fa
      version: -1
      name: Initialize `ASM - Remediation`
      description: Resets grid field to [] in the case that the playbook was run again
        or if the alert was created before the field was installed through content.
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      asmremediation:
        simple: '[]'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1250,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: e5288c19-1493-4726-8ba4-59c8fdea5424
    type: regular
    task:
      id: e5288c19-1493-4726-8ba4-59c8fdea5424
      version: -1
      name: Initialize `ASM - Notification`
      description: Resets grid field to [] in the case that the playbook was run again
        or if the alert was created before the field was installed through content.
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      asmnotification:
        simple: '[]'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 870,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 8d8281fa-9ff2-41ec-8140-d533f0b8e1c3
    type: regular
    task:
      id: 8d8281fa-9ff2-41ec-8140-d533f0b8e1c3
      version: -1
      name: Initialize `ASM - Service Detection`
      description: Resets grid field to [] in the case that the playbook was run again
        or if the alert was created before the field was installed through content.
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      asmservicedetection:
        simple: '[]'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 100,
          "y": 670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: b5709fde-9808-46f3-8112-9a4acbd01e3c
    type: regular
    task:
      id: b5709fde-9808-46f3-8112-9a4acbd01e3c
      version: -1
      name: Initialize `ASM - Alert Summary`
      description: Resets grid field to [] in the case that the playbook was run again
        or if the alert was created before the field was installed through content.
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      asmalertsummary:
        simple: '[]'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 3b7f9544-8c41-4519-823d-7dc850f10fa8
    type: regular
    task:
      id: 3b7f9544-8c41-4519-823d-7dc850f10fa8
      version: -1
      name: delete context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 490,
          "y": 140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 21fdda2f-da5e-4bfd-8ceb-c44dbf7abc76
    type: playbook
    task:
      id: 21fdda2f-da5e-4bfd-8ceb-c44dbf7abc76
      version: -1
      name: Cortex ASM - ASM Alert
      playbookName: Cortex ASM - ASM Alert
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      AutomatedRemediation:
        simple: "False"
      OwnerNotificationBody:
        simple: |+
          Infosec identified a security risk on an external service potentially owned by your team: ${alert.name}

          Description: ${alert.details}

      OwnerNotificationSubject:
        simple: A new security risk was identified on an external service owned by
          your team
      RemediationRule:
        simple: Remediation-Security-Group
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 20,
          "y": 985
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: ca54dc4c-6da1-4b4f-83be-e9cd36e3718f
    type: regular
    task:
      id: ca54dc4c-6da1-4b4f-83be-e9cd36e3718f
      version: -1
      name: Dev Check
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      asmdevcheck:
        simple: "false"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 64ec29fa-2819-4634-895a-41fdd7a24148
    type: regular
    task:
      id: 64ec29fa-2819-4634-895a-41fdd7a24148
      version: -1
      name: Initialize `ASM - Cloud`
      description: Resets grid field to [] in the case that the playbook was run again
        or if the alert was created before the field was installed through content.
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      asmcloud:
        simple: '[]'
      asmservicedetection:
        simple: '[]'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -320,
          "y": 680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1040,
        "width": 2280,
        "x": -650,
        "y": 40
      }
    }
  }
inputs: []
outputs: []
