id: Cortex ASM - Tenable.io Enrichment
version: -1
name: Cortex ASM - Tenable.io Enrichment
description: Given the IP address this playbook enriches Tenable.io information relevant to ASM alerts.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 15002d0c-2c5e-42de-8e7f-7f93c7e5d921
    type: start
    task:
      id: 15002d0c-2c5e-42de-8e7f-7f93c7e5d921
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 560,
          "y": -880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 0d66d3b7-0bb8-4281-857b-a67f341f37ef
    type: title
    task:
      id: 0d66d3b7-0bb8-4281-857b-a67f341f37ef
      version: -1
      name: |
        Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 120,
          "y": 1140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 68945e50-5bfb-4dd8-86e8-0db781462a74
    type: condition
    task:
      id: 68945e50-5bfb-4dd8-86e8-0db781462a74
      version: -1
      name: Is Tenable.io enabled and is Input value defined?
      description: Determines if the Tenable.io integration instance is configured and Input values are defined to pull enrichment data.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "27"
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Tenable.io
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
          right:
            value: {}
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.IPAddress
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 560,
          "y": -740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: a9c9cdf2-2119-41e7-81b8-4d64fced0764
    type: regular
    task:
      id: a9c9cdf2-2119-41e7-81b8-4d64fced0764
      version: -1
      name: Lookup asset information by IP
      description: Retrieves details for the specified asset to include custom attributes.
      script: '|||tenable-io-get-asset-details'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      ip:
        complex:
          root: inputs.IPAddress
          transformers:
          - operator: uniq
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 560,
          "y": -500
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 294b4636-dccb-42d3-896f-1d484c859806
    type: condition
    task:
      id: 294b4636-dccb-42d3-896f-1d484c859806
      version: -1
      name: Was an asset found?
      description: Check whether the last command returned Tenable.io asset information or not.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "27"
      "yes":
      - "26"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: TenableIO
                accessor: AssetDetails
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 560,
          "y": -310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 4b72c01c-f52d-4215-8d8e-e277707e786c
    type: regular
    task:
      id: 4b72c01c-f52d-4215-8d8e-e277707e786c
      version: -1
      name: Extract indicators
      description: commands.local.cmd.extract.indicators
      script: Builtin|||extractIndicators
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      text:
        complex:
          root: TenableIO
          accessor: AssetDetails
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1270,
          "y": 425
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 791ea5bf-f418-4849-8150-2078a2876d5a
    type: condition
    task:
      id: 791ea5bf-f418-4849-8150-2078a2876d5a
      version: -1
      name: Was an email found?
      description: Check whether the last command extracted an email address or not.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "17"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: ExtractedIndicators
                accessor: Email
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1270,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: ca4b3174-eec8-41f7-8bd5-e4edbcc6ca9c
    type: regular
    task:
      id: ca4b3174-eec8-41f7-8bd5-e4edbcc6ca9c
      version: -1
      name: Set service owner grid field
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      gridfield:
        simple: asmserviceowner
      keys:
        simple: Name,Email,Source,Timestamp
      val1:
        simple: n/a
      val2:
        complex:
          root: ExtractedIndicators
          accessor: Email
      val3:
        simple: Tenable.io
      val4:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: TimeStampToDate
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1460,
          "y": 930
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 2734e900-1db5-4b1f-842d-a93e4c748c15
    type: regular
    task:
      id: 2734e900-1db5-4b1f-842d-a93e4c748c15
      version: -1
      name: Get current time
      description: |
        Retrieves the current date and time.
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1460,
          "y": 770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 1e965fed-8642-4dd4-8164-8bd5c05f92af
    type: title
    task:
      id: 1e965fed-8642-4dd4-8164-8bd5c05f92af
      version: -1
      name: Service Owner
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1270,
          "y": 280
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: bd2f49d4-bfb5-4db5-8594-22cdfa2d1f18
    type: title
    task:
      id: bd2f49d4-bfb5-4db5-8594-22cdfa2d1f18
      version: -1
      name: Set Field
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "19"
      - "21"
      - "23"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 560,
          "y": 115
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: f876b403-878f-4797-8a08-18671c4d9922
    type: title
    task:
      id: f876b403-878f-4797-8a08-18671c4d9922
      version: -1
      name: System IDs
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "22"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 430,
          "y": 280
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: bad0dba9-aa7a-46de-8b7e-b34634bdc168
    type: regular
    task:
      id: bad0dba9-aa7a-46de-8b7e-b34634bdc168
      version: -1
      name: Set system IDs grid field (Asset_id)
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      gridfield:
        simple: asmsystemids
      keys:
        simple: Type,ID,Link
      val1:
        simple: Tenable.io-Asset_id
      val2:
        complex:
          root: TenableIO.AssetDetails
          accessor: id
      val3:
        complex:
          root: TenableIO.AssetDetails
          accessor: id
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: https://cloud.tenable.com/tio/app.html#/assets-uw/hosts-assets/details/
              suffix:
                value:
                  simple: /findings?
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 430,
          "y": 425
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: b8a184c1-bdbf-43d3-86f8-262fe326fecb
    type: title
    task:
      id: b8a184c1-bdbf-43d3-86f8-262fe326fecb
      version: -1
      name: Tags
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "25"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 850,
          "y": 280
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "24":
    id: "24"
    taskid: 4bf11bde-e5a9-4451-884c-a98d60b6fddc
    type: regular
    task:
      id: 4bf11bde-e5a9-4451-884c-a98d60b6fddc
      version: -1
      name: Set tags grid field
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      gridfield:
        simple: asmtags
      keys:
        simple: Key,Value,Source
      val1:
        complex:
          root: TenableIO.AssetDetails.tags
          accessor: tag_key
      val2:
        complex:
          root: TenableIO.AssetDetails.tags
          accessor: tag_value
      val3:
        simple: Tenable.io
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 850,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "25":
    id: "25"
    taskid: df65bf86-0c7c-4cb3-8c16-80841b636158
    type: condition
    task:
      id: df65bf86-0c7c-4cb3-8c16-80841b636158
      version: -1
      name: Was a tag present?
      description: Check whether the last command returned Tenable.io asset with one or more tags.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "24"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: TenableIO.AssetDetails.tags
                accessor: tag_key
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 850,
          "y": 425
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "26":
    id: "26"
    taskid: ec3e1094-6ba9-4e17-83cc-c4b94513f8df
    type: regular
    task:
      id: ec3e1094-6ba9-4e17-83cc-c4b94513f8df
      version: -1
      name: Set ASM enrichment status to true
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Instead of a value you can enter `TIMESTAMP` to get the current timestamp in ISO format. For example:
        `!GridFieldSetup keys=ip,src,timestamp val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" val3="TIMESTAMP" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      gridfield:
        simple: asmenrichmentstatus
      keys:
        simple: source,record_exists,timestamp
      val1:
        simple: Tenable.io
      val2:
        simple: "true"
      val3:
        simple: TIMESTAMP
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 560,
          "y": -60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "27":
    id: "27"
    taskid: e0ae79e3-f89f-45ef-88e0-c95529cde214
    type: regular
    task:
      id: e0ae79e3-f89f-45ef-88e0-c95529cde214
      version: -1
      name: Set ASM enrichment status to false
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Instead of a value you can enter `TIMESTAMP` to get the current timestamp in ISO format. For example:
        `!GridFieldSetup keys=ip,src,timestamp val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" val3="TIMESTAMP" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      gridfield:
        simple: asmenrichmentstatus
      keys:
        simple: source,record_exists,timestamp
      val1:
        simple: Tenable.io
      val2:
        simple: "false"
      val3:
        simple: TIMESTAMP
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 120,
          "y": -60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "13_26_yes": 0.58,
      "15_2_#default#": 0.2,
      "25_2_#default#": 0.34
    },
    "paper": {
      "dimensions": {
        "height": 2085,
        "width": 1720,
        "x": 120,
        "y": -880
      }
    }
  }
inputs:
- key: ""
  value: {}
  required: false
  description: ""
  playbookInputQuery:
    query: ""
    queryEntity: indicators
    results:
    daterange:
      fromdate: 0001-01-01T00:00:00Z
      todate: 0001-01-01T00:00:00Z
      period:
        by: ""
        byto: ""
        byfrom: ""
        tovalue:
        fromvalue:
        field: ""
      fromdatelicenseval: 0001-01-01T00:00:00Z
    runFromLastJobTime: true
- key: IPAddress
  value:
    complex:
      root: alert
      accessor: remoteip
      transformers:
      - operator: uniq
  required: true
  description: IP addresses to enrich.
  playbookInputQuery:
outputs:
- contextPath: AWS.EC2.Instances
  description: AWS EC2 information.
  type: unknown
- contextPath: AWS.EC2.SecurityGroups
  description: AWS Security group information.
  type: unknown
- contextPath: AWS.IAM.Users
  description: AWS IAM information.
  type: unknown
tests:
- No tests (auto formatted)
fromversion: 6.5.0
