id: Cortex ASM - Remediation Confirmation Scan
version: -1
name: Cortex ASM - Remediation Confirmation Scan
description: Playbook for RCS Scan creation and polling.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5785981e-18ef-498c-8bf8-b6b2ea8c48c8
    type: start
    task:
      id: 5785981e-18ef-498c-8bf8-b6b2ea8c48c8
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -10
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 18683d7a-546e-4904-892f-338f2b8aae2f
    type: regular
    task:
      id: 18683d7a-546e-4904-892f-338f2b8aae2f
      version: -1
      name: Start Remediation Confirmation Scan
      description: Starts a new Remediation Confirmation Scan or gets an existing scan ID
      script: '|||asm-start-remediation_confirmation_scan'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      alert_internal_id:
        simple: ${alert.id}
      attack_surface_rule_id:
        simple: ${alert.asmattacksurfaceruleid}
      service_id:
        simple: ${alert.asmserviceid}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 398add1d-8d75-4ebe-8b81-5748caa68ddd
    type: condition
    task:
      id: 398add1d-8d75-4ebe-8b81-5748caa68ddd
      version: -1
      name: Did the Remediation Confirmation Scan successfully start?
      description: Conditional check for if the Remediation Confirmation Scan was successfully started or not.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "15"
      "Yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "Yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: ASM.RemediationScan
                accessor: scan_creation_status
            iscontext: true
          right:
            value:
              simple: created
        - operator: containsGeneral
          left:
            value:
              complex:
                root: ASM.RemediationScan
                accessor: scan_creation_status
            iscontext: true
          right:
            value:
              simple: existing
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: d7c32370-abfd-421f-8d1a-8515d7322de0
    type: playbook
    task:
      id: d7c32370-abfd-421f-8d1a-8515d7322de0
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      Ids:
        simple: ${ASM.RemediationScan.scanId}
      Interval:
        simple: "10"
      PollingCommandArgName:
        simple: scan_id
      PollingCommandName:
        simple: asm-get-remediation-confirmation-scan-status
      Timeout:
        simple: "180"
      dt:
        simple: ASM.RemediationScan(val.status !== ‘SUCCESS’)
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 220,
          "y": 560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: e397b3da-c37b-4d9b-84ee-59b1b92b6b73
    type: title
    task:
      id: e397b3da-c37b-4d9b-84ee-59b1b92b6b73
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1700
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 28a3a05d-b196-4ee1-8e39-897acc71ff4c
    type: regular
    task:
      id: 28a3a05d-b196-4ee1-8e39-897acc71ff4c
      version: -1
      name: Retrieve Remediation Information from RCS
      description: Get status of an existing remediation confirmation scan.
      script: '|||asm-get-remediation-confirmation-scan-status'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      scan_id:
        complex:
          root: ASM.RemediationScan
          accessor: scanId
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 220,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 34efe486-7034-49ae-8d27-e2cea521db18
    type: condition
    task:
      id: 34efe486-7034-49ae-8d27-e2cea521db18
      version: -1
      name: Did the Remediation Confirmation Scan complete?
      description: Conditional check for if the Remediation Confirmation Scan was successful or not.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      Complete:
      - "10"
      Failure:
      - "12"
      Timeout:
      - "14"
    separatecontext: false
    conditions:
    - label: Complete
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: ASM.RemediationScan
                accessor: status
            iscontext: true
          right:
            value:
              simple: SUCCESS
    - label: Failure
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: ASM.RemediationScan
                accessor: status
            iscontext: true
          right:
            value:
              simple: FAILED_ERROR
    - label: Timeout
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: ASM.RemediationScan
                accessor: status
            iscontext: true
          right:
            value:
              simple: FAILED_TIMEOUT
        - operator: isEqualString
          left:
            value:
              complex:
                root: ASM.RemediationScan
                accessor: status
            iscontext: true
          right:
            value:
              simple: IN_PROGRESS
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 220,
          "y": 900
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: c8367bc0-3138-4d78-8f86-e0b119956e1f
    type: regular
    task:
      id: c8367bc0-3138-4d78-8f86-e0b119956e1f
      version: -1
      name: Set service detection grid field
      description: Populate asmservicedetection field with "ScanNum,ScanDone,ScanResult,Timestamp,ScanState"
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      gridfield:
        simple: asmservicedetection
      keys:
        simple: ScanNum,ScanDone,ScanResult,Timestamp,ScanState
      val1:
        complex:
          root: ASM.RemediationScan
          accessor: scanId
      val2:
        complex:
          root: ScanDone
          transformers:
          - operator: SetIfEmpty
            args:
              applyIfEmpty: {}
              defaultValue:
                value:
                  simple: "null"
      val3:
        complex:
          root: ASM.RemediationScan
          accessor: result
      val4:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: TimeStampToDate
      val5:
        complex:
          root: ASM.RemediationScan
          accessor: status
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -220,
          "y": 1320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 9382be1b-2982-48a6-80ca-3c46c388baab
    type: regular
    task:
      id: 9382be1b-2982-48a6-80ca-3c46c388baab
      version: -1
      name: Get current time
      description: |
        Retrieves the current date and time.
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -220,
          "y": 1140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: bd505ca5-af63-437a-809f-acd63386e388
    type: regular
    task:
      id: bd505ca5-af63-437a-809f-acd63386e388
      version: -1
      name: Set service detection grid field
      description: Populate asmservicedetection field with "ScanNum,ScanDone,ScanResult,Timestamp,ScanState"
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      gridfield:
        simple: asmservicedetection
      keys:
        simple: ScanNum,ScanDone,ScanResult,Timestamp,ScanState
      val1:
        complex:
          root: ASM.RemediationScan
          accessor: scanId
      val2:
        simple: "false"
      val3:
        simple: N/A
      val4:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: TimeStampToDate
      val5:
        complex:
          root: ASM.RemediationScan
          accessor: status
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 220,
          "y": 1320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 5cc9a40c-623c-4c09-83e4-498834efdb2e
    type: regular
    task:
      id: 5cc9a40c-623c-4c09-83e4-498834efdb2e
      version: -1
      name: Get current time
      description: |
        Retrieves the current date and time.
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 220,
          "y": 1145
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: ebc5acc6-9ef6-451e-8956-b21a9fc569f0
    type: regular
    task:
      id: ebc5acc6-9ef6-451e-8956-b21a9fc569f0
      version: -1
      name: Set service detection grid field
      description: Populate asmservicedetection field with "ScanNum,ScanDone,ScanResult,Timestamp,ScanState"
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      gridfield:
        simple: asmservicedetection
      keys:
        simple: ScanNum,ScanDone,ScanResult,Timestamp,ScanState
      val1:
        complex:
          root: ASM.RemediationScan
          accessor: scanId
      val2:
        simple: "false"
      val3:
        simple: N/A
      val4:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: TimeStampToDate
      val5:
        complex:
          root: ASM.RemediationScan
          accessor: status
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 670,
          "y": 1320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 0cdf3670-da85-4f66-84e7-f3c8d6a24307
    type: regular
    task:
      id: 0cdf3670-da85-4f66-84e7-f3c8d6a24307
      version: -1
      name: Get current time
      description: |
        Retrieves the current date and time.
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 670,
          "y": 1140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: cb6dffe7-a4c2-4af1-878c-10eb16603709
    type: title
    task:
      id: cb6dffe7-a4c2-4af1-878c-10eb16603709
      version: -1
      name: Scan Not Available
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "2_3_Yes": 0.38
    },
    "paper": {
      "dimensions": {
        "height": 1775,
        "width": 1710,
        "x": -220,
        "y": -10
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.8.0
tests:
- No tests (auto formatted)
