id: Cortex ASM - Qualys Enrichment
version: -1
name: Cortex ASM - Qualys Enrichment
description: Given the IP address this playbook enriches information from Qualys assets.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 388441bb-83c7-44b4-8228-c10d3a4bab74
    type: start
    task:
      id: 388441bb-83c7-44b4-8228-c10d3a4bab74
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -20
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 9424140c-14f5-4115-88c5-c20a04c1129a
    type: condition
    task:
      id: 9424140c-14f5-4115-88c5-c20a04c1129a
      version: -1
      name: Is Qualys enabled and input value defined?
      description: Determines if the "Qualys" integration instance is enabled in order to find assets and asset tags.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "19"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: QualysV2
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
          right:
            value: {}
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.QualysIP
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 75b65f6d-c35d-4c6b-87a1-53fba44d9ade
    type: title
    task:
      id: 75b65f6d-c35d-4c6b-87a1-53fba44d9ade
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -70,
          "y": 1860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 301a21d1-395b-4e3d-89ca-5a98105d456d
    type: regular
    task:
      id: 301a21d1-395b-4e3d-89ca-5a98105d456d
      version: -1
      name: Lookup host information in Qualys
      description: View host information in the Qualys account.
      script: QualysV2|||qualys-host-list
      type: regular
      iscommand: true
      brand: QualysV2
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      details:
        simple: All
      ips:
        complex:
          root: inputs.QualysIP
      show_cloud_tags:
        simple: "1"
      show_tags:
        simple: "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 581c36a1-32b6-42ae-8686-292a399d1b3c
    type: title
    task:
      id: 581c36a1-32b6-42ae-8686-292a399d1b3c
      version: -1
      name: Service Owner
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 250,
          "y": 1060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 01668533-6ed8-420a-8cfb-6aa5aeecacb4
    type: title
    task:
      id: 01668533-6ed8-420a-8cfb-6aa5aeecacb4
      version: -1
      name: Set Field
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "5"
      - "7"
      - "8"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 60ee6e86-5b2f-4588-8389-b7c47fb540f6
    type: title
    task:
      id: 60ee6e86-5b2f-4588-8389-b7c47fb540f6
      version: -1
      name: System IDs
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 690,
          "y": 1060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: e144d234-e2bb-42fe-8b6c-7adf2debd72f
    type: title
    task:
      id: e144d234-e2bb-42fe-8b6c-7adf2debd72f
      version: -1
      name: Tags
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 30abe8b0-654f-4b49-8447-412362634bcd
    type: condition
    task:
      id: 30abe8b0-654f-4b49-8447-412362634bcd
      version: -1
      name: Was a host found?
      description: Check whether the last command returned Qualys asset information or not.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "19"
      "yes":
      - "17"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Qualys
                accessor: Endpoint
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 530
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 21e9747a-4d22-4368-80e0-9964da14108a
    type: condition
    task:
      id: 21e9747a-4d22-4368-80e0-9964da14108a
      version: -1
      name: Was an owner found?
      description: Check whether the last command has owner or not.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Qualys.Endpoint
                accessor: OWNER
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 250,
          "y": 1210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 24a233a0-e121-4058-88d9-8cc0abd9278b
    type: regular
    task:
      id: 24a233a0-e121-4058-88d9-8cc0abd9278b
      version: -1
      name: Set service owner grid field
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      gridfield:
        simple: asmserviceowner
      keys:
        simple: Name,Email,Source,Timestamp
      val1:
        complex:
          root: Qualys.Endpoint
          accessor: OWNER
          transformers:
          - operator: uniq
      val2:
        simple: n/a
      val3:
        simple: Qualys
      val4:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: TimeStampToDate
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 250,
          "y": 1590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 7b445fba-007d-4112-8814-d9be53af992a
    type: regular
    task:
      id: 7b445fba-007d-4112-8814-d9be53af992a
      version: -1
      name: Get current time
      description: |
        Retrieves the current date and time.
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 250,
          "y": 1430
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 30666ce4-dba7-4b63-8822-da8be0f58d22
    type: regular
    task:
      id: 30666ce4-dba7-4b63-8822-da8be0f58d22
      version: -1
      name: Set tags grid field
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      gridfield:
        simple: asmtags
      keys:
        simple: Key,Value,Source
      val1:
        complex:
          root: Qualys.Endpoint.TAGS
          accessor: TAG
          transformers:
          - operator: getField
            args:
              field:
                value:
                  simple: NAME
          - operator: uniq
      val2:
        complex:
          root: Qualys.Endpoint.TAGS
          accessor: TAG
          transformers:
          - operator: getField
            args:
              field:
                value:
                  simple: TAG_ID
          - operator: uniq
      val3:
        simple: Qualys
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 1a5c86b1-37f6-413f-8091-9f1ca67156ad
    type: condition
    task:
      id: 1a5c86b1-37f6-413f-8091-9f1ca67156ad
      version: -1
      name: Was a tag present?
      description: Check whether the last command returned Qualys host with one or more tags.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Qualys.Endpoint
                accessor: TAGS
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 1b763ff4-9970-4f7c-8ebe-57106d5670f8
    type: regular
    task:
      id: 1b763ff4-9970-4f7c-8ebe-57106d5670f8
      version: -1
      name: Set system IDs grid field (Host id)
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      gridfield:
        simple: asmsystemids
      keys:
        simple: Type,ID,Link
      val1:
        simple: Qualys-Host_id
      val2:
        complex:
          root: Qualys.Endpoint
          accessor: ID
      val3:
        simple: n/a
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 690,
          "y": 1360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: a735c5bb-1f9a-49df-80e7-84b96878a1bf
    type: regular
    task:
      id: a735c5bb-1f9a-49df-80e7-84b96878a1bf
      version: -1
      name: Set ASM - Enrichment Status
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Instead of a value you can enter `TIMESTAMP` to get the current timestamp in ISO format. For example:
        `!GridFieldSetup keys=ip,src,timestamp val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" val3="TIMESTAMP" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      gridfield:
        simple: asmenrichmentstatus
      keys:
        simple: source,record_exists,timestamp
      val1:
        simple: Qualys
      val2:
        simple: "true"
      val3:
        simple: TIMESTAMP
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 1bbdc0bb-2552-49df-8bcf-41ff2c3d01d3
    type: regular
    task:
      id: 1bbdc0bb-2552-49df-8bcf-41ff2c3d01d3
      version: -1
      name: Set ASM - Enrichment Status
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Instead of a value you can enter `TIMESTAMP` to get the current timestamp in ISO format. For example:
        `!GridFieldSetup keys=ip,src,timestamp val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" val3="TIMESTAMP" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      gridfield:
        simple: asmenrichmentstatus
      keys:
        simple: source,record_exists,timestamp
      val1:
        simple: Qualys
      val2:
        simple: "false"
      val3:
        simple: TIMESTAMP
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -70,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "10_2_#default#": 0.36,
      "9_17_yes": 0.47
    },
    "paper": {
      "dimensions": {
        "height": 1945,
        "width": 1560,
        "x": -70,
        "y": -20
      }
    }
  }
inputs:
- key: QualysIP
  value:
    complex:
      root: alert
      accessor: remoteip
      transformers:
      - operator: uniq
  required: true
  description: Remote IP in alert.
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.8.0
