id: Cortex ASM - Detect Service
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: Cortex ASM - Detect Service
description: Playbook that checks to see if an existing ASM service ID is available. If it is available it will begin a Xpanse Remediation Confirmation Scan.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0572001c-322b-438d-8bec-667b631d18a8
    type: start
    task:
      id: 0572001c-322b-438d-8bec-667b631d18a8
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "43"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 540,
          "y": -210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: e227705c-072b-4c39-8f0a-fabcd441c509
    type: title
    task:
      id: e227705c-072b-4c39-8f0a-fabcd441c509
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 550,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: c7c170aa-4424-429b-8efd-c37b4104c6d2
    type: title
    task:
      id: c7c170aa-4424-429b-8efd-c37b4104c6d2
      version: -1
      name: Non-Service Based Alert
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 810,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "43":
    id: "43"
    taskid: f8e5dec9-9a30-4dc7-87d4-09f323d87a91
    type: condition
    task:
      id: f8e5dec9-9a30-4dc7-87d4-09f323d87a91
      version: -1
      name: Is there a ASM service ID?
      description: Conditional task to check for an existing ASM service ID. The Remediation Confirmation Scan can only be used to scan existing service IDs found by Xpanse.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "44"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: alert
                accessor: asmserviceid
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 540,
          "y": -60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "44":
    id: "44"
    taskid: f4497855-c82f-494e-8e5c-700bba179753
    type: playbook
    task:
      id: f4497855-c82f-494e-8e5c-700bba179753
      version: -1
      name: 'Cortex ASM - Remediation Confirmation Scan'
      playbookName: Cortex ASM - Remediation Confirmation Scan
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 290,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "43_44_yes": 0.64
    },
    "paper": {
      "dimensions": {
        "height": 665,
        "width": 900,
        "x": 290,
        "y": -210
      }
    }
  }
inputs:
- key: RemoteIP
  value:
    complex:
      root: alert
      accessor: remoteip
  required: false
  description: Remote IP address in the alert.
  playbookInputQuery:
- key: RemotePort
  value:
    complex:
      root: alert
      accessor: remoteport
  required: false
  description: Remote port number in the alert.
  playbookInputQuery:
- key: ASMRuleID
  value:
    complex:
      root: alert
      accessor: asmattacksurfaceruleid
  required: true
  description: Attack Surface Management Rule ID.
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.8.0
