id: Cortex ASM - Prisma Cloud Enrichment
version: -1
name: Cortex ASM - Prisma Cloud Enrichment
description: Given the IP address this playbook enriches information from Prisma Cloud.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 095a3981-cf9b-490a-84b3-31ef90d827b7
    type: start
    task:
      id: 095a3981-cf9b-490a-84b3-31ef90d827b7
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 160
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: e3c366c6-191b-4cd2-8b50-852eb392654c
    type: playbook
    task:
      id: e3c366c6-191b-4cd2-8b50-852eb392654c
      version: -1
      name: Prisma Cloud - Find Public Cloud Resource by Public IP v2
      playbookName: Prisma Cloud - Find Public Cloud Resource by Public IP v2
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      CloudProvider:
        complex:
          root: inputs.cloudProvider
      PublicIPAddress:
        complex:
          root: inputs.remoteIP
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 25735200-95aa-496b-8556-b02c06567484
    type: title
    task:
      id: 25735200-95aa-496b-8556-b02c06567484
      version: -1
      name: Set field
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
      - "7"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 8a5cf504-8baa-4be5-8503-772feb08f9d7
    type: condition
    task:
      id: 8a5cf504-8baa-4be5-8503-772feb08f9d7
      version: -1
      name: Is there instance information?
      description: Determines if there is instance information obtained from Prisma Cloud.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: PrismaCloud
                accessor: Attribution
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -30,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 60e18105-f14a-4fe1-8c08-c87d16491527
    type: title
    task:
      id: 60e18105-f14a-4fe1-8c08-c87d16491527
      version: -1
      name: System IDs
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 200,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: a885cd4d-d129-496d-8bdf-5f238ada3dc7
    type: regular
    task:
      id: a885cd4d-d129-496d-8bdf-5f238ada3dc7
      version: -1
      name: Set system IDs grid field (instance ID)
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Example of command:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      gridfield:
        simple: asmsystemids
      keys:
        simple: type,id,link
      val1:
        simple: PRISMACLOUD-INSTANCE-ID
      val2:
        complex:
          root: PrismaCloud.Attribution
          accessor: rrn
      val3:
        simple: n/a
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 200,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: d99019ac-eb13-49f2-8e71-5ef22cd69e45
    type: condition
    task:
      id: d99019ac-eb13-49f2-8e71-5ef22cd69e45
      version: -1
      name: Are there tags information?
      description: Determines if there is tag information obtained from Prisma Cloud.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: PrismaCloud.Config.data
                accessor: tags
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 23055ee8-e62c-4986-8924-b235fea76e8c
    type: title
    task:
      id: 23055ee8-e62c-4986-8924-b235fea76e8c
      version: -1
      name: Tags
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 630,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 97d94a49-81f0-470e-8ef8-947a241be5bc
    type: regular
    task:
      id: 97d94a49-81f0-470e-8ef8-947a241be5bc
      version: -1
      name: Set tags grid field
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Example of command:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      gridfield:
        simple: asmtags
      keys:
        simple: key,value,source
      val1:
        complex:
          root: PrismaCloud.Config.data
          accessor: tags
          transformers:
          - operator: jmespath
            args:
              expression:
                value:
                  simple: keys(@)
      val2:
        complex:
          root: PrismaCloud.Config.data
          accessor: tags
          transformers:
          - operator: jmespath
            args:
              expression:
                value:
                  simple: values(@)
      val3:
        simple: PrismaCloud
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 630,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 8dcaad78-96e9-4433-846d-9dc3ff968c23
    type: regular
    task:
      id: 8dcaad78-96e9-4433-846d-9dc3ff968c23
      version: -1
      name: Set true flag for completed enrichment
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: asm_fields_set_for_prisma
      value:
        simple: "true"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 410,
          "y": 1190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 4b5b4004-5e8a-4167-8fd7-8f1142dc7c9d
    type: title
    task:
      id: 4b5b4004-5e8a-4167-8fd7-8f1142dc7c9d
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 410,
          "y": 1840
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: c40b4535-4e9a-4bf1-8d6f-c3eb85d36181
    type: regular
    task:
      id: c40b4535-4e9a-4bf1-8d6f-c3eb85d36181
      version: -1
      name: Set ASM enrichment status to true
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Instead of a value you can enter `TIMESTAMP` to get the current timestamp in ISO format. For example:
        `!GridFieldSetup keys=ip,src,timestamp val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" val3="TIMESTAMP" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      gridfield:
        simple: asmenrichmentstatus
      keys:
        simple: source,record_exists,timestamp
      val1:
        simple: Prisma Cloud
      val2:
        simple: "true"
      val3:
        simple: TIMESTAMP
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 200,
          "y": 1640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: ef2e8f2a-2268-4d0c-8a2a-7dfdec25fdf4
    type: condition
    task:
      id: ef2e8f2a-2268-4d0c-8a2a-7dfdec25fdf4
      version: -1
      name: Was enrichment performed?
      description: Check if enrichment was performed by checking for a value of true in the relevant flag variable.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              simple: asm_fields_set_for_prisma
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 410,
          "y": 1430
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 62bad94b-39ea-4845-8da4-53c36a3d8bb7
    type: regular
    task:
      id: 62bad94b-39ea-4845-8da4-53c36a3d8bb7
      version: -1
      name: Set ASM enrichment status to false
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Instead of a value you can enter `TIMESTAMP` to get the current timestamp in ISO format. For example:
        `!GridFieldSetup keys=ip,src,timestamp val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" val3="TIMESTAMP" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      gridfield:
        simple: asmenrichmentstatus
      keys:
        simple: source,record_exists,timestamp
      val1:
        simple: Prisma Cloud
      val2:
        simple: "false"
      val3:
        simple: TIMESTAMP
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 620,
          "y": 1640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "3_13_#default#": 0.2,
      "7_13_#default#": 0.22
    },
    "paper": {
      "dimensions": {
        "height": 1745,
        "width": 1270,
        "x": -30,
        "y": 160
      }
    }
  }
inputs:
- key: remoteIP
  value:
    complex:
      root: alert
      accessor: remoteip
  required: true
  description: IP address of service.
  playbookInputQuery:
- key: cloudProvider
  value: {}
  required: false
  description: Cloud service provider.
  playbookInputQuery:
outputs: []
fromversion: 6.8.0
tests:
- No tests (auto formatted)
