id: Cortex ASM - Service Ownership
version: -1
name: Cortex ASM - Service Ownership
description: Identifies and recommends the most likely owners of the service, additionally citing an explanation and ranking score for each.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 57e985be-0db1-4244-832b-b27213d31989
    type: start
    task:
      id: 57e985be-0db1-4244-832b-b27213d31989
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 170,
          "y": -170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 86e45d85-5d9a-44f6-8bcb-9386e8a824a8
    type: condition
    task:
      id: 86e45d85-5d9a-44f6-8bcb-9386e8a824a8
      version: -1
      name: Is the ASM Cloud Project field defined?
      description: Determine whether a service account was included among the potential service owners.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: alert.asmcloud
                accessor: Project
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 855
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 3f99ac12-8e98-428b-81dc-527a6f8f7e98
    type: regular
    task:
      id: 3f99ac12-8e98-428b-81dc-527a6f8f7e98
      version: -1
      name: Lookup project owner
      description: Retrieves the IAM access control policy for the specified project.
      script: GCP-IAM|||gcp-iam-project-iam-policy-get
      type: regular
      iscommand: true
      brand: GCP-IAM
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      project_name:
        complex:
          root: alert.asmcloud
          accessor: Project
          transformers:
          - operator: uniq
          - operator: concat
            args:
              prefix:
                value:
                  simple: projects/
              suffix: {}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: b5acafc7-f647-4210-881b-13d9d5f252f8
    type: regular
    task:
      id: b5acafc7-f647-4210-881b-13d9d5f252f8
      version: -1
      name: Add project owner to service owner grid field
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Example of command:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      gridfield:
        simple: asmserviceowner
      keys:
        simple: Name,Email,Source,Timestamp
      val1:
        simple: n/a
      val2:
        complex:
          root: GCPIAM.Policy.bindings
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: GCPIAM.Policy.bindings.role
                iscontext: true
              right:
                value:
                  simple: roles/owner
          accessor: members
          transformers:
          - operator: replace
            args:
              limit: {}
              replaceWith: {}
              toReplace:
                value:
                  simple: 'user:'
      val3:
        simple: Owner of GCP project where service account is defined
      val4:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: TimeStampToDate
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 2b90887f-a6ba-47a6-875f-622c8285dffc
    type: regular
    task:
      id: 2b90887f-a6ba-47a6-875f-622c8285dffc
      version: -1
      name: Normalize and rank likely service owners
      description: Recommend most likely service owners from those surfaced by Cortex ASM Enrichment.
      scriptName: RankServiceOwners
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      owners:
        simple: ${alert.asmserviceowner}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 790,
          "y": 1600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 7ca75c22-47ac-40a9-84f2-fc68e43d7d53
    type: regular
    task:
      id: 7ca75c22-47ac-40a9-84f2-fc68e43d7d53
      version: -1
      name: Back up service owners gridfield
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Example of command:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      gridfield:
        simple: asmserviceownerunrankedraw
      keys:
        simple: name,email,source,timestamp
      val1:
        complex:
          root: alert
          accessor: asmserviceowner
          transformers:
          - operator: getField
            args:
              field:
                value:
                  simple: Name
      val2:
        complex:
          root: alert
          accessor: asmserviceowner
          transformers:
          - operator: getField
            args:
              field:
                value:
                  simple: Email
      val3:
        complex:
          root: alert
          accessor: asmserviceowner
          transformers:
          - operator: getField
            args:
              field:
                value:
                  simple: Source
      val4:
        complex:
          root: alert
          accessor: asmserviceowner
          transformers:
          - operator: getField
            args:
              field:
                value:
                  simple: Timestamp
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 570,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: b0bddb17-8cec-405c-8441-478959b9e8c4
    type: regular
    task:
      id: b0bddb17-8cec-405c-8441-478959b9e8c4
      version: -1
      name: Get current time
      description: |
        Retrieves the current date and time.
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1260
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 1bad13f3-b959-46d9-8b56-90282a3afdcf
    type: condition
    task:
      id: 1bad13f3-b959-46d9-8b56-90282a3afdcf
      version: -1
      name: Is asmserviceowner populated?
      description: Determines if the asmserviceowner field exists and if the common fields within it also exists.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: alert
                accessor: asmserviceowner
            iscontext: true
          right:
            value: {}
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: alert.asmserviceowner
                accessor: Email
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: alert.asmserviceowner
                accessor: Name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: alert.asmserviceowner
                accessor: Source
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 170,
          "y": -10
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 97716817-0eab-418a-8517-40dc54d22f00
    type: title
    task:
      id: 97716817-0eab-418a-8517-40dc54d22f00
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 170,
          "y": 1820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 1e322e1d-faef-420f-81bf-56d3d57eb27d
    type: condition
    task:
      id: 1e322e1d-faef-420f-81bf-56d3d57eb27d
      version: -1
      name: Is GCP - IAM enabled?
      description: Determines if the GCP-IAM integration instance is configured.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: GCP-IAM
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 615
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 7d2c20d1-9e85-44ec-8dd0-cc1848251282
    type: condition
    task:
      id: 7d2c20d1-9e85-44ec-8dd0-cc1848251282
      version: -1
      name: What provider is this service?
      description: Determines which cloud provider the service is in order to direct to the correct steps for gathering data to rank owners.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      GCP:
      - "12"
    separatecontext: false
    conditions:
    - label: GCP
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: ASM.ExternalService
                accessor: externally_detected_providers
            iscontext: true
          right:
            value:
              simple: Google
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 570,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "12_2_yes": 0.61,
      "12_6_#default#": 0.23,
      "14_12_GCP": 0.54,
      "2_4_yes": 0.65,
      "2_6_#default#": 0.28,
      "9_10_#default#": 0.34
    },
    "paper": {
      "dimensions": {
        "height": 2055,
        "width": 1000,
        "x": 170,
        "y": -170
      }
    }
  }
inputs: []
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.8.0
