id: Cortex ASM - Prisma Cloud Enrichment
version: -1
name: Cortex ASM - Prisma Cloud Enrichment
description: Given the IP address this playbook enriches information from Prisma Cloud.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 4b6f60e3-76ef-4ccb-8ea2-8c90b0865e7c
    type: start
    task:
      id: 4b6f60e3-76ef-4ccb-8ea2-8c90b0865e7c
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 160
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: c725c4a6-521e-42a3-8aa2-24a77a345693
    type: playbook
    task:
      id: c725c4a6-521e-42a3-8aa2-24a77a345693
      version: -1
      name: Prisma Cloud - Find Public Cloud Resource by Public IP v2
      playbookName: Prisma Cloud - Find Public Cloud Resource by Public IP v2
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      CloudProvider:
        complex:
          root: inputs.cloudProvider
      PublicIPAddress:
        complex:
          root: inputs.remoteIP
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: f53679c5-8481-4e1d-8665-2a813fdbf1fa
    type: title
    task:
      id: f53679c5-8481-4e1d-8665-2a813fdbf1fa
      version: -1
      name: Set field
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
      - "7"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 8973a7e6-feff-430e-8c14-63652703672c
    type: condition
    task:
      id: 8973a7e6-feff-430e-8c14-63652703672c
      version: -1
      name: Is there instance information?
      description: Determines if there is instance information obtained from Prisma Cloud.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: PrismaCloud
                accessor: Attribution
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -30,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: cebbb06b-b66f-40a8-8ffe-64b519d35b2e
    type: title
    task:
      id: cebbb06b-b66f-40a8-8ffe-64b519d35b2e
      version: -1
      name: System IDs
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 200,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 65c34a1a-b100-461f-8051-84c92d4d273c
    type: regular
    task:
      id: 65c34a1a-b100-461f-8051-84c92d4d273c
      version: -1
      name: Set Instance IDs grid field
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Example of command:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      gridfield:
        simple: asmsystemids
      keys:
        simple: Type,ID,Link
      val1:
        simple: PrismaCloud-ID
      val2:
        complex:
          root: PrismaCloud.Attribution
          accessor: rrn
      val3:
        simple: n/a
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 200,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: a0eb3fce-5e60-41c6-8354-adac2fd7fefc
    type: condition
    task:
      id: a0eb3fce-5e60-41c6-8354-adac2fd7fefc
      version: -1
      name: Are there tags information?
      description: Determines if there is tag information obtained from Prisma Cloud.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: PrismaCloud.Config.data
                accessor: tags
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 038c6b2e-881c-49af-89c6-fae19a559c2e
    type: title
    task:
      id: 038c6b2e-881c-49af-89c6-fae19a559c2e
      version: -1
      name: Tags
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 630,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 0ce1d2ab-60ad-4ce8-8202-b94561685413
    type: regular
    task:
      id: 0ce1d2ab-60ad-4ce8-8202-b94561685413
      version: -1
      name: Set tags grid field
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Example of command:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      gridfield:
        simple: asmtags
      keys:
        simple: Key,Value,Source
      val1:
        complex:
          root: PrismaCloud.Config.data
          accessor: tags
          transformers:
          - operator: jmespath
            args:
              expression:
                value:
                  simple: keys(@)
      val2:
        complex:
          root: PrismaCloud.Config.data
          accessor: tags
          transformers:
          - operator: jmespath
            args:
              expression:
                value:
                  simple: values(@)
      val3:
        simple: PrismaCloud
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 630,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 025d9d62-38c1-4c2c-8d17-fe2621e02777
    type: regular
    task:
      id: 025d9d62-38c1-4c2c-8d17-fe2621e02777
      version: -1
      name: Set flag for completed enrichment
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      key:
        simple: asm_fields_set_for_rapid7
      value:
        simple: "true"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 410,
          "y": 1190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 4d7919d0-8f76-4114-81f6-c7bba790f784
    type: title
    task:
      id: 4d7919d0-8f76-4114-81f6-c7bba790f784
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 410,
          "y": 1840
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: d9237a5b-a269-445b-84d1-2c8dc5387946
    type: regular
    task:
      id: d9237a5b-a269-445b-84d1-2c8dc5387946
      version: -1
      name: Set ASM enrichment status to true
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Instead of a value you can enter `TIMESTAMP` to get the current timestamp in ISO format. For example:
        `!GridFieldSetup keys=ip,src,timestamp val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" val3="TIMESTAMP" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      gridfield:
        simple: asmenrichmentstatus
      keys:
        simple: source,record_exists,timestamp
      val1:
        simple: Rapid7
      val2:
        simple: "true"
      val3:
        simple: TIMESTAMP
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 200,
          "y": 1640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: b184ee4a-93c4-42c4-8658-84898e2dbf99
    type: condition
    task:
      id: b184ee4a-93c4-42c4-8658-84898e2dbf99
      version: -1
      name: Was enrichment performed?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              simple: asm_fields_set_for_rapid7
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 410,
          "y": 1430
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 25c918d2-c939-4223-8c9f-52aa9ecadca5
    type: regular
    task:
      id: 25c918d2-c939-4223-8c9f-52aa9ecadca5
      version: -1
      name: Set ASM enrichment status to false
      description: |-
        Automation used to more easily populate a grid field.  This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Instead of a value you can enter `TIMESTAMP` to get the current timestamp in ISO format. For example:
        `!GridFieldSetup keys=ip,src,timestamp val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" val3="TIMESTAMP" gridfiled="gridfield"`
      scriptName: GridFieldSetup
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      gridfield:
        simple: asmenrichmentstatus
      keys:
        simple: source,record_exists,timestamp
      val1:
        simple: Rapid7
      val2:
        simple: "false"
      val3:
        simple: TIMESTAMP
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 620,
          "y": 1640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "3_13_#default#": 0.2,
      "7_13_#default#": 0.22
    },
    "paper": {
      "dimensions": {
        "height": 1745,
        "width": 1270,
        "x": -30,
        "y": 160
      }
    }
  }
inputs:
- key: remoteIP
  value:
    complex:
      root: alert
      accessor: remoteip
  required: true
  description: IP address of service.
  playbookInputQuery:
- key: cloudProvider
  value: {}
  required: false
  description: Cloud service provider.
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.8.0
